### ISSUE TITLE
Buildpack cannot be used on latest Heroku environment (heroku-20)

### ISSUE THREAD

**Issue by wasamasa** [raxod502/heroku-buildpack-emacs#1]
```
remote: -----> Emacs Lisp app detected
remote: -----> Install Emacs
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
[...]
remote: 100  180M  100  180M    0     0  26.4M      0  0:00:06  0:00:06 --:--:-- 26.5M
remote: /tmp/build_a0b86dce/emacs/bin/emacs: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
remote:  !     Push rejected, failed to compile Emacs Lisp app.
remote: 
remote:  !     Push failed
[...]
```

To work around this, I've used `heroku stack:set heroku-18`. Might want to create stack-specific buildpacks instead?

**Comment by raxod502** [comment]
Ugh, that sucks. Rather than creating stack-specific buildpacks, I think a better solution would be to simply detect the stack version in use (assuming that's possible), and download an appropriate binary. I'll take a look at this now, since it seems like a critical issue for usage of the buildpack.

Darned soname changes.

**Comment by raxod502** [comment]
This should now be fixed out of the box. The stack is detected automatically and an appropriate version of Emacs is installed. Additionally, Emacs versions up to 27.2 are now available, defaulting to the latest released and overridable using the `EMACS_VERSION` app config variable.
