### ISSUE TITLE
Emacs 28.1

### ISSUE THREAD

**Issue by wasamasa** [raxod502/heroku-buildpack-emacs#2]
Hello again. Emacs 28.1 has been released, so that alone may be reason enough to do whatever needs to be done for it to show up as buildpack option.

That aside, I've noticed it supports a `--sandbox=FILE` option for reading seccomp BPF filters, so that may be interesting for sandboxing. If you have made any experience with this, I'd be very interested.

**Comment by raxod502** [comment]
Sure, I can add Emacs 28 in a few days. No knowledge of the BPF features, do you think it would be relevant for this buildpack?

**Comment by wasamasa** [comment]
The reason I mentioned this was because one of the commits mentioned seccomp. So if that's no longer relevant, then the option is only good for additional sandboxing.

**Comment by raxod502** [comment]
Uploaded https://github.com/raxod502/heroku-buildpack-emacs/releases/tag/heroku-20-emacs-28.1. The seccomp stuff was just for backwards compatibility with pre-27.1 versions of Emacs and can be removed now. I just haven't done so for simplicity.

**Comment by wasamasa** [comment]
Thank you! I've looked more into the seccomp stuff and noticed that Emacs ships with a filter. However, even that filter is too strict to launch it with, so it seems it's a premature feature.
